#!/usr/bin/env python3
"""Splitter for ritual-generated giant `file1.cpp` translation units.

Run as a final pass after `qt_ritual` has produced (or refreshed) crate
sources. For each affected ritual Qt crate, this turns:

    file1.cpp:
        #include "<crate>_c_global.h"
        // ~1k lines of Q_OBJECT slot/signal wrapper classes
        extern "C" {
            // ~14k RITUAL_EXPORT free functions
        } // extern "C"
        #include "file1.moc"

into:

    file1.h:
        #ifndef ...
        #include "<crate>_c_global.h"
        // the Q_OBJECT classes
        #endif

    file{1..N}.cpp:
        #include "<crate>_c_global.h"
        #include "file1.h"
        extern "C" {
            // 1/N of the free functions
        } // extern "C"

The header is named `file1.h` (not `file1_classes.h`) so CMake's AUTOMOC
pairs it with `file1.cpp` by basename and scans it for Q_OBJECT. Without
that pairing, AUTOMOC would never scan the header and moc'd symbols
(staticMetaObject, vtable, typeinfo, emit_) would be undefined at link.

The existing CMakeLists.txt picks shards up via `file(GLOB *.cpp)`, so
no CMake change is required. The original `#include "file1.moc"` line is
dropped — header-paired Q_OBJECT classes feed `mocs_compilation.cpp`
automatically.

Usage:
    split_generated_cpp.py [--shards N] [--min-fns N] [crate ...]

If no crates are listed, every directory under `output/out/*/c_lib/` whose
`file1.cpp` exceeds `--min-fns` RITUAL_EXPORT functions is split. Already-
split shards (file2..fileN.cpp + file1.h) are removed first to keep the
output set deterministic on shard-count changes.
"""

import argparse
import sys
from pathlib import Path

DEFAULT_SHARDS = 8
DEFAULT_MIN_FNS = 1000

ROOT = Path(__file__).resolve().parent.parent / "output" / "out"


def discover_crates(root: Path):
    return sorted(
        p.parent.parent.name
        for p in root.glob("*/c_lib/file1.cpp")
    )


def already_split(c_lib: Path, global_header: str) -> bool:
    """A crate is considered already split if file1.cpp starts with the
    two include lines this script emits."""
    cpp_path = c_lib / "file1.cpp"
    if not cpp_path.exists():
        return False
    head = cpp_path.read_text().splitlines()[:2]
    return (
        len(head) >= 2
        and head[0] == f'#include "{global_header}"'
        and head[1] == '#include "file1.h"'
    )


def reconstruct_original(c_lib: Path, global_header: str) -> list[str]:
    """Rebuild a `file1.cpp`-equivalent buffer from existing shards + file1.h
    so the splitter can re-shard at a different N. The output is the same
    `splitlines(keepends=True)` shape the splitter expects below."""
    header_lines = (c_lib / "file1.h").read_text().splitlines(keepends=True)
    # Strip the include-guard wrapping and the `#include "<global>.h"` line
    # the script emits at the top of file1.h.
    classes: list[str] = []
    in_body = False
    for ln in header_lines:
        stripped = ln.rstrip("\n")
        if not in_body:
            if stripped.startswith("// Class generated by") or stripped.startswith("class "):
                in_body = True
            else:
                continue
        if stripped.startswith("#endif"):
            break
        classes.append(ln)
    # Trim trailing blank lines so repeated --force re-shards don't grow
    # the header by one blank line each cycle.
    while classes and classes[-1].strip() == "":
        classes.pop()

    bodies: list[str] = []
    shard_paths = sorted(
        c_lib.glob("file*.cpp"),
        key=lambda p: int(p.stem[4:]),
    )
    for shard in shard_paths:
        shard_lines = shard.read_text().splitlines(keepends=True)
        try:
            start = next(
                i for i, ln in enumerate(shard_lines)
                if ln.rstrip("\n") == 'extern "C" {'
            ) + 1
            end = next(
                i for i in range(len(shard_lines) - 1, -1, -1)
                if shard_lines[i].rstrip("\n") == '} // extern "C"'
            )
        except StopIteration:
            continue
        bodies.extend(shard_lines[start:end])

    return (
        [f'#include "{global_header}"\n']
        + classes
        + ['extern "C" {\n']
        + bodies
        + ['} // extern "C"\n']
    )


def split_crate(crate: str, shards: int, min_fns: int, force: bool) -> str:
    c_lib = ROOT / crate / "c_lib"
    cpp_path = c_lib / "file1.cpp"
    if not cpp_path.exists():
        return f"skip {crate}: no file1.cpp"
    global_header = f"{crate}_c_global.h"
    if not (c_lib / global_header).exists():
        return f"skip {crate}: expected global header {global_header} not found"

    if already_split(c_lib, global_header):
        if not force:
            return f"skip {crate}: file1.cpp already split (pass --force to re-shard)"
        lines = reconstruct_original(c_lib, global_header)
    else:
        lines = cpp_path.read_text().splitlines(keepends=True)

    extern_start = next(
        (i for i, ln in enumerate(lines) if ln.rstrip("\n") == 'extern "C" {'),
        None,
    )
    extern_end = next(
        (
            i for i in range(len(lines) - 1, -1, -1)
            if lines[i].rstrip("\n") == '} // extern "C"'
        ),
        None,
    )
    if extern_start is None or extern_end is None:
        return f"skip {crate}: extern C boundaries not found"

    # The first line is `#include "<crate>_c_global.h"`; everything between
    # that and `extern "C" {` is the Q_OBJECT class definitions.
    classes_lines = lines[1:extern_start]
    body_lines = lines[extern_start + 1: extern_end]

    # Each RITUAL_EXPORT function starts on a line whose first token is
    # `RITUAL_EXPORT`. Use those line indices as shard boundaries.
    fn_starts = [i for i, ln in enumerate(body_lines) if ln.startswith("RITUAL_EXPORT")]
    n_fns = len(fn_starts)
    if n_fns == 0:
        return f"skip {crate}: no RITUAL_EXPORT functions found"
    if n_fns < min_fns:
        return f"skip {crate}: {n_fns} fns < --min-fns {min_fns}"

    # Drop any old shards from a previous run so the output set matches
    # the current shard count exactly.
    for stale in c_lib.glob("file*.cpp"):
        stale.unlink()
    (c_lib / "file1.h").unlink(missing_ok=True)

    (c_lib / "file1.h").write_text(
        '#ifndef RITUAL_FILE1_H\n'
        '#define RITUAL_FILE1_H\n'
        '\n'
        f'#include "{global_header}"\n'
        '\n'
        + ''.join(classes_lines)
        + '\n#endif // RITUAL_FILE1_H\n'
    )

    chunk = (n_fns + shards - 1) // shards
    shard_count = 0
    for s in range(shards):
        start_idx = s * chunk
        if start_idx >= n_fns:
            break
        end_idx = min(start_idx + chunk, n_fns)
        body_start = fn_starts[start_idx]
        body_end = fn_starts[end_idx] if end_idx < n_fns else len(body_lines)
        shard_body = body_lines[body_start:body_end]

        (c_lib / f"file{s + 1}.cpp").write_text(
            f'#include "{global_header}"\n'
            '#include "file1.h"\n'
            'extern "C" {\n'
            + ''.join(shard_body)
            + '} // extern "C"\n'
        )
        shard_count += 1

    return (f"{crate}: {n_fns} fns -> {shard_count} shards, "
            f"{len(classes_lines)} class lines -> file1.h")


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--shards", type=int, default=DEFAULT_SHARDS,
                    help=f"number of shards per crate (default {DEFAULT_SHARDS})")
    ap.add_argument("--min-fns", type=int, default=DEFAULT_MIN_FNS,
                    help=f"skip crates with fewer than this many RITUAL_EXPORT "
                         f"functions (default {DEFAULT_MIN_FNS})")
    ap.add_argument("--force", action="store_true",
                    help="re-shard even if file1.cpp already looks split "
                         "(reconstructs the body from existing shards)")
    ap.add_argument("crates", nargs="*",
                    help="crate names to split; if empty, discover them")
    args = ap.parse_args(argv)

    if args.shards < 1:
        ap.error("--shards must be >= 1")

    crates = args.crates or discover_crates(ROOT)
    if not crates:
        print(f"no crates found under {ROOT}")
        return 1

    for crate in crates:
        print(split_crate(crate, args.shards, args.min_fns, args.force))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
