[package]
name = "ritual_common"
edition = "2018"
version = "0.4.0"
authors = ["Pavel Strakhov <ri@idzaaus.org>"]
description = "Common utilities for ritual and ritual_build"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-qt/ritual"

[dependencies]
anyhow = "1" # error handling
serde = "1"       # serialization
serde_derive = "1"
serde_json = "1"
bitcode = { version = "0.6", features = ["serde"] }
num_cpus = "1"  # detect preferred task count
toml = "1" # toml generation and parsing
itertools = "0.14"
log = "0.4"
semver = "1"
pathdiff = "0.2"
shell-words = "1"
dunce = "1"
